import { ButtonComponent } from "@syncfusion/ej2-react-buttons";
import {
  ChangeEventArgs,
  DropDownListComponent,
} from "@syncfusion/ej2-react-dropdowns";
import {
  ChangedEventArgs,
  TextBoxComponent,
} from "@syncfusion/ej2-react-inputs";
import { DialogComponent } from "@syncfusion/ej2-react-popups";
import { useRef, useState } from "react";
import { ErrorBoundary } from "react-error-boundary";
import { useTranslation } from "react-i18next";

import { Error, Table, Column } from "@/domain";
import {
  DataService,
  RecordsProvider,
  useRecordsContext,
} from "@/hooks/useRecords";
import { showAlertDialog } from "@/utilities/ui";

import { ErrorFallback } from "../shared/ErrorFallback";
import { TableColumnSettingsContentDialog } from "./TableColumnSettingsContentDialog";
import { TableVersionSettingsDialog } from "./TableVersionSettingsDialog";

type NewTable = Pick<
  Table,
  "Description" | "DisplayName" | "Comments" | "Name" | "Type"
>;

function TableSettingsDialog({
  closeDialog,
  record,
}: {
  closeDialog: () => void;
  record: Table | null;
}) {
  const { t } = useTranslation(["common", "tables", "column-type", "errors"]);
  const refDialog = useRef<DialogComponent | null>(null);

  const dataService: DataService<Column> = {
    getRecords: async (): Promise<Column[]> => {
      let columnsStr = localStorage.getItem("columns");
      if (columnsStr === null) {
        localStorage.setItem("columns", JSON.stringify(INITIAL_COLUMNS));
        columnsStr = JSON.stringify(INITIAL_COLUMNS);
      }
      const columns = JSON.parse(columnsStr) as Column[];
      return columns.filter((column) => column.TableId === record?.Id);
    },
    addRecord: async (record: Omit<Column, "@odata.etag" | "Id">) => {
      let columnsStr = localStorage.getItem("columns");
      if (columnsStr === null) {
        localStorage.setItem("columns", JSON.stringify(INITIAL_COLUMNS));
        columnsStr = JSON.stringify(INITIAL_COLUMNS);
      }
      const columns = JSON.parse(columnsStr) as Column[];
      const taleColumns = columns.filter(
        (column) => column.TableId === record.TableId
      );
      let id = Math.max(...taleColumns.map((c: Column) => c.Id)) + 1;
      record.Id = id;
      columns.push(record);
      localStorage.setItem("columns", JSON.stringify(columns));
      return record;
    },
    editRecord: async (record: Column) => {
      let columnsStr = localStorage.getItem("columns");
      if (columnsStr === null) {
        localStorage.setItem("columns", JSON.stringify(INITIAL_COLUMNS));
        columnsStr = JSON.stringify(INITIAL_COLUMNS);
      }
      const columns = JSON.parse(columnsStr) as Column[];
      const newColumns = columns.map((c: Column) => {
        if (c.Id === record.Id) {
          return record;
        }
        return c;
      });
      localStorage.setItem("columns", JSON.stringify(newColumns));
      return record;
    },
    deleteRecord: async (record: Column) => {
      let columnsStr = localStorage.getItem("columns");
      if (columnsStr === null) {
        localStorage.setItem("columns", JSON.stringify(INITIAL_COLUMNS));
        columnsStr = JSON.stringify(INITIAL_COLUMNS);
      }
      const columns = JSON.parse(columnsStr) as Column[];
      const newColumns = columns.filter((c: Column) => c.Id !== record.Id);
      localStorage.setItem("columns", JSON.stringify(newColumns));
    },
  };

  const [recordData, setRecordData] = useState<Table | NewTable>(
    () =>
      record ?? {
        Comments: "",
        Description: "",
        DisplayName: "",
        Name: "",
        Type: 1,
      }
  );
  const { addRecord, editRecord } = useRecordsContext();

  function validateTable(table: Pick<Table, "DisplayName">): boolean {
    const errorMessages: string[] = [];
    if (table.DisplayName.length === 0) {
      errorMessages.push(
        t("field-name-is-required", { ns: "errors", name: t("name") }) as string
      );
    }
    if (errorMessages.length) {
      showAlertDialog({
        title: t("error", { ns: "common" }) as string,
        content: errorMessages.join("<br />"),
      });
    }
    return errorMessages.length === 0;
  }

  function handleChangeRecordData(fieldName: string, value: number | string) {
    const dataToSet: Partial<Table> = {
      [fieldName]: value,
    };
    if (fieldName === "DisplayName") {
      dataToSet.Name = value as string;
    }
    setRecordData({
      ...recordData,
      ...dataToSet,
    });
  }

  async function handleClickSave() {
    const isValid = validateTable(recordData);
    if (!isValid) return;

    try {
      if (record === null) {
        await addRecord(recordData as NewTable);
      } else {
        await editRecord(recordData as Table);
      }
      const dialogInstance = refDialog.current!;
      dialogInstance.hide();
    } catch (error) {
      const { code, message } = error as Error;
      showAlertDialog({
        title: t("error", { ns: "common" }) as string,
        content: message,
      });
    }
  }

  return (
    <DialogComponent
      ref={refDialog}
      buttons={[
        {
          buttonModel: {
            content: t("save") as string,
            isPrimary: true,
          },
          click: handleClickSave,
        },
        {
          buttonModel: {
            content: t("cancel") as string,
          },
          click: () => {
            const dialogInstance = refDialog.current!;
            dialogInstance.hide();
          },
        },
      ]}
      className={
        record === null
          ? "table-settings-dialog table-settings-dialog--add"
          : "table-settings-dialog table-settings-dialog--edit"
      }
      header={`${
        record === null ? (t("add") as string) : (t("edit") as string)
      } ${t("table") as string}`}
      isModal={true}
      target={"#__next"}
      showCloseIcon={true}
      close={() => {
        closeDialog();
      }}
    >
      <div
        className={`table-settings-dialog__content ${
          record === null
            ? "table-settings-dialog__content--add"
            : "table-settings-dialog__content--edit"
        }`}
      >
        <div className="table-settings-dialog__content__first-section">
          <section className="table-settings-dialog__content__form">
            <label htmlFor="DisplayName">{t("name")}*:</label>
            <TextBoxComponent
              id="DisplayName"
              name="DisplayName"
              type="text"
              value={recordData.DisplayName}
              change={({ isInteracted, value }: ChangedEventArgs) => {
                if (isInteracted) {
                  handleChangeRecordData("DisplayName", value?.trim() ?? "");
                }
              }}
            />

            <label htmlFor="Type">{t("type")}:</label>
            <DropDownListComponent
              id="Type"
              name="Type"
              dataSource={[
                { text: t("table") as string, value: 1 },
                { text: t("document-repository") as string, value: 2 },
              ]}
              enabled={record === null}
              fields={{ text: "text", value: "value" }}
              value={recordData.Type}
              change={({ isInteracted, value }: ChangeEventArgs) => {
                if (isInteracted) {
                  handleChangeRecordData("Type", Number(value));
                }
              }}
            />

            <label htmlFor="Description">{t("description")}:</label>
            <TextBoxComponent
              id="Description"
              name="Description"
              multiline={true}
              type="text"
              value={recordData.Description}
              change={({ isInteracted, value }: ChangedEventArgs) => {
                if (isInteracted) {
                  handleChangeRecordData("Description", value?.trim() ?? "");
                }
              }}
            />

            <label htmlFor="Comments">{t("comments")}:</label>
            <TextBoxComponent
              id="Comments"
              name="Comments"
              multiline={true}
              type="text"
              value={recordData.Comments}
              change={({ isInteracted, value }: ChangedEventArgs) => {
                if (isInteracted) {
                  handleChangeRecordData("Comments", value?.trim() ?? "");
                }
              }}
            />
          </section>
          {record !== null && (
            <section className="table-settings-dialog__content__button-panel">
              <div className="button-panel__row">
                <TableVersionSettingsDialog {...(recordData as Table)} />
              </div>
              <div className="button-panel__row">
                <ButtonComponent
                  type="button"
                  onClick={() => console.log("dialog-title-edit-permissions")}
                >
                  {t("dialog-title-edit-permissions", { ns: "tables" })}
                </ButtonComponent>
              </div>
              <div className="button-panel__row">
                <ButtonComponent
                  type="button"
                  onClick={() => console.log("dialog-title-edit-forms")}
                >
                  {t("dialog-title-edit-forms", { ns: "tables" })}
                </ButtonComponent>
              </div>
            </section>
          )}
        </div>
        {record !== null && (
          <ErrorBoundary FallbackComponent={ErrorFallback}>
            <RecordsProvider
              // dataServiceSettings={{
              //   tableName: "Columns",
              //   query: `?$filter=TableId eq ${record.Id}`,
              // }}
              dataService={dataService}
            >
              <section className="table-settings-dialog__content__columns">
                <TableColumnSettingsContentDialog {...record} />
              </section>
            </RecordsProvider>
          </ErrorBoundary>
        )}
      </div>
    </DialogComponent>
  );
}

const INITIAL_COLUMNS = [
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 100,
    SiteId: null,
    DisplayName: "Id",
    Description: null,
    IsSystem: true,
    ColumnType: "integerNumber",
    Comments: null,
    IsRequired: true,
    Name: "Id",
    TableId: 1,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"Id"},"DescriptionTranslations":{"es":""}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 101,
    SiteId: null,
    DisplayName: "Creado por",
    Description: null,
    IsSystem: true,
    ColumnType: "user",
    Comments: null,
    IsRequired: true,
    Name: "CreatedUser",
    TableId: 1,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"Creado por"},"DescriptionTranslations":{"es":""}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 102,
    SiteId: null,
    DisplayName: "Creado",
    Description: null,
    IsSystem: true,
    ColumnType: "dateTime",
    Comments: null,
    IsRequired: true,
    Name: "CreatedDate",
    TableId: 1,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"Creado"},"DescriptionTranslations":{"es":""}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 103,
    SiteId: null,
    DisplayName: "Modificado por",
    Description: null,
    IsSystem: true,
    ColumnType: "user",
    Comments: null,
    IsRequired: true,
    Name: "ModifiedUser",
    TableId: 1,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"Modificado por"},"DescriptionTranslations":{"es":""}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 104,
    SiteId: null,
    DisplayName: "Modificado",
    Description: null,
    IsSystem: true,
    ColumnType: "dateTime",
    Comments: null,
    IsRequired: true,
    Name: "ModifiedDate",
    TableId: 1,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"Modificado"},"DescriptionTranslations":{"es":""}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 105,
    SiteId: null,
    DisplayName: "Nombre",
    Description: null,
    IsSystem: false,
    ColumnType: "text",
    Comments: null,
    IsRequired: false,
    Name: "Name",
    TableId: 1,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"Nombre"},"DescriptionTranslations":{"es":""}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 106,
    SiteId: null,
    DisplayName: "Descripción",
    Description: null,
    IsSystem: false,
    ColumnType: "textArea",
    Comments: null,
    IsRequired: false,
    Name: "Description",
    TableId: 1,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"Descripción"},"DescriptionTranslations":{"es":""}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 107,
    SiteId: null,
    DisplayName: "Día de la Independencia",
    Description: null,
    IsSystem: false,
    ColumnType: "date",
    Comments: null,
    IsRequired: false,
    Name: "IndependenceDay",
    TableId: 1,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"Día de la Independencia"},"DescriptionTranslations":{"es":""}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 108,
    SiteId: null,
    DisplayName: "Población",
    Description: null,
    IsSystem: false,
    ColumnType: "integerNumber",
    Comments: null,
    IsRequired: false,
    Name: "Population",
    TableId: 1,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"Población"},"DescriptionTranslations":{"es":"Conjunto de personas que habitan una determinada área geográfica."}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 109,
    SiteId: null,
    DisplayName: "PIB",
    Description: null,
    IsSystem: false,
    ColumnType: "integerNumber",
    Comments: null,
    IsRequired: false,
    Name: "GDP",
    TableId: 1,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"PIB"},"DescriptionTranslations":{"es":""}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 110,
    SiteId: null,
    DisplayName: "Es miembro de la ONU",
    Description: null,
    IsSystem: false,
    ColumnType: "boolean",
    Comments: null,
    IsRequired: false,
    Name: "IsMemberOfUN",
    TableId: 1,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"Es miembro de la ONU"},"DescriptionTranslations":{"es":""}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 111,
    SiteId: null,
    DisplayName: "Presidente",
    Description: null,
    IsSystem: false,
    ColumnType: "user",
    Comments: null,
    IsRequired: false,
    Name: "President",
    TableId: 1,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"Presidente"},"DescriptionTranslations":{"es":""}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 112,
    SiteId: null,
    DisplayName: "Continente",
    Description: null,
    IsSystem: false,
    ColumnType: "lookup",
    Comments: null,
    IsRequired: false,
    Name: "Continent",
    TableId: 1,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: 4,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"Continente"},"DescriptionTranslations":{"es":""},"editColumnName":"Name","extraColumns":[],"cascadingSettings":{"parentName":"","lookupTableParentName":""}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 113,
    SiteId: null,
    DisplayName: "Departamentos2",
    Description: null,
    IsSystem: false,
    ColumnType: "textArea",
    Comments: null,
    IsRequired: false,
    Name: "Departments2",
    TableId: 1,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"ColumnType":"relation","DisplayNameTranslations":{"es":"Departamentos2"},"DescriptionTranslations":{"es":""},"relatedTable":{"tableName":"Departments2","relatedColumnName":"Country","isWeakRelationship":true},"relatedType":"grid","relatedTypeSettings":{"columns":[{"behaviorType":"","displayType":"editable","headerText":"","name":"Name","stackedHeaderText":""},{"behaviorType":"","displayType":"editable","headerText":"","name":"Files","stackedHeaderText":""}],"order":[{"field":"","direction":"ascending"}],"pagingRowTotal":10,"editSettings":{"mode":"dialog","allowAdding":true,"allowEditing":true,"allowDeleting":true}},"preLoadData":{"columns":[{"related":"Name","preLoad":"Name","useAsKey":true}],"filter":{"currentTableColumn":"President","overwriteRecords":"ask","preLoadTableColumn":"Mayor","type":"dinamic","value":null},"saveAsDraft":false,"source":"Departments2PreLoadData"}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 114,
    SiteId: null,
    DisplayName: "RichText",
    Description: null,
    IsSystem: false,
    ColumnType: "textArea",
    Comments: null,
    IsRequired: false,
    Name: "RichText",
    TableId: 1,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"RichText"},"DescriptionTranslations":{"es":""},"isRichText":true}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 115,
    SiteId: null,
    DisplayName: "DecimalNumberPercentage",
    Description: null,
    IsSystem: false,
    ColumnType: "decimalNumber",
    Comments: null,
    IsRequired: false,
    Name: "DecimalNumberPercentage",
    TableId: 1,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"DecimalNumberPercentage"},"DescriptionTranslations":{"es":""},"isPercentage":true}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 116,
    SiteId: null,
    DisplayName: "MultipleUser",
    Description: null,
    IsSystem: false,
    ColumnType: "multipleUser",
    Comments: null,
    IsRequired: false,
    Name: "MultipleUser",
    TableId: 1,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"MultipleUser"},"DescriptionTranslations":{"es":""}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 117,
    SiteId: null,
    DisplayName: "MultipleGroup",
    Description: null,
    IsSystem: false,
    ColumnType: "multipleGroup",
    Comments: null,
    IsRequired: false,
    Name: "MultipleGroup",
    TableId: 1,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"MultipleGroup"},"DescriptionTranslations":{"es":""}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 118,
    SiteId: null,
    DisplayName: "UserOrGroup",
    Description: null,
    IsSystem: false,
    ColumnType: "userOrGroup",
    Comments: null,
    IsRequired: false,
    Name: "UserOrGroup",
    TableId: 1,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"UserOrGroup"},"DescriptionTranslations":{"es":""}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 119,
    SiteId: null,
    DisplayName: "MultipleUsersAndGroups",
    Description: null,
    IsSystem: false,
    ColumnType: "multipleUsersAndGroups",
    Comments: null,
    IsRequired: false,
    Name: "MultipleUsersAndGroups",
    TableId: 1,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"MultipleUsersAndGroups"},"DescriptionTranslations":{"es":""}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 120,
    SiteId: null,
    DisplayName: "MultipleLookup",
    Description: null,
    IsSystem: false,
    ColumnType: "multipleLookup",
    Comments: null,
    IsRequired: false,
    Name: "MultipleLookup",
    TableId: 1,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: 6,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"MultipleLookup"},"DescriptionTranslations":{"es":""},"editColumnName":"Name","extraColumns":[],"cascadingSettings":{"parentName":"","lookupTableParentName":""}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 121,
    SiteId: null,
    DisplayName: "DateTime",
    Description: null,
    IsSystem: false,
    ColumnType: "dateTime",
    Comments: null,
    IsRequired: false,
    Name: "DateTime",
    TableId: 1,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"DateTime"},"DescriptionTranslations":{"es":""}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 122,
    SiteId: null,
    DisplayName: "Time",
    Description: null,
    IsSystem: false,
    ColumnType: "time",
    Comments: null,
    IsRequired: false,
    Name: "Time",
    TableId: 1,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"Time"},"DescriptionTranslations":{"es":""}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 123,
    SiteId: null,
    DisplayName: "Archivos iniciales",
    Description: null,
    IsSystem: false,
    ColumnType: "file",
    Comments: null,
    IsRequired: false,
    Name: "Files",
    TableId: 1,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"Archivos iniciales"},"DescriptionTranslations":{"es":""}, "fileSettings": {"isMultiple":false, "allowedExtensions":["img"], "minFileSize": 10000, "maxFileSize": 1500000, "minFilesCount": 1, "maxFilesCount": 3},"relatedTable":{"tableName":"Countries__Files","relatedColumnName":"ParentEntity","isWeakRelationship":true}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 200,
    SiteId: null,
    DisplayName: "Id",
    Description: null,
    IsSystem: true,
    ColumnType: "integerNumber",
    Comments: null,
    IsRequired: true,
    Name: "Id",
    TableId: 2,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"Id"},"DescriptionTranslations":{"es":""}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 201,
    SiteId: null,
    DisplayName: "Creado por",
    Description: null,
    IsSystem: true,
    ColumnType: "user",
    Comments: null,
    IsRequired: true,
    Name: "CreatedUser",
    TableId: 2,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"Creado por"},"DescriptionTranslations":{"es":""}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 202,
    SiteId: null,
    DisplayName: "Creado",
    Description: null,
    IsSystem: true,
    ColumnType: "dateTime",
    Comments: null,
    IsRequired: true,
    Name: "CreatedDate",
    TableId: 2,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"Creado"},"DescriptionTranslations":{"es":""}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 203,
    SiteId: null,
    DisplayName: "Modificado por",
    Description: null,
    IsSystem: true,
    ColumnType: "user",
    Comments: null,
    IsRequired: true,
    Name: "ModifiedUser",
    TableId: 2,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"Modificado por"},"DescriptionTranslations":{"es":""}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 204,
    SiteId: null,
    DisplayName: "Modificado",
    Description: null,
    IsSystem: true,
    ColumnType: "dateTime",
    Comments: null,
    IsRequired: true,
    Name: "ModifiedDate",
    TableId: 2,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"Modificado"},"DescriptionTranslations":{"es":""}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 205,
    SiteId: null,
    DisplayName: "Nombre",
    Description: null,
    IsSystem: false,
    ColumnType: "text",
    Comments: null,
    IsRequired: false,
    Name: "Name",
    TableId: 2,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"Nombre"},"DescriptionTranslations":{"es":""}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 206,
    SiteId: null,
    DisplayName: "País",
    Description: null,
    IsSystem: false,
    ColumnType: "lookup",
    Comments: null,
    IsRequired: false,
    Name: "Country",
    TableId: 2,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: 1,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"País"},"DescriptionTranslations":{"es":""},"editColumnName":"Name","extraColumns":[{"name":"IndependenceDay","displayName":null},{"name":"Continent.Name","displayName":"Continente"}],"cascadingSettings":{"parentName":"","lookupTableParentName":""}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 207,
    SiteId: null,
    DisplayName: "Municipios",
    Description: null,
    IsSystem: false,
    ColumnType: "textArea",
    Comments: null,
    IsRequired: false,
    Name: "Municipalities",
    TableId: 2,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"ColumnType":"relation","DisplayNameTranslations":{"es":"Municipios"},"DescriptionTranslations":{"es":""},"relatedTable":{"tableName":"Municipalities","relatedColumnName":"Department","isWeakRelationship":true},"relatedType":"grid","relatedTypeSettings":{"columns":[{"behaviorType":"","displayType":"editable","headerText":"","name":"Name","stackedHeaderText":""},{"behaviorType":"","displayType":"editable","headerText":"","name":"Files","stackedHeaderText":""}],"order":[{"field":"","direction":"ascending"}],"pagingRowTotal":0,"editSettings":{"mode":"inline","allowAdding":true,"allowEditing":true,"allowDeleting":true}},"preLoadData":{"columns":[],"filter":{"currentTableColumn":"","overwriteRecords":"ask","preLoadTableColumn":"","type":"dinamic","value":null},"saveAsDraft":true,"source":""}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
  {
    "@odata.etag": 'W/"2023-08-16T12:39:37.047Z"',
    Id: 208,
    SiteId: null,
    DisplayName: "Archivos iniciales",
    Description: null,
    IsSystem: false,
    ColumnType: "file",
    Comments: null,
    IsRequired: false,
    Name: "Files",
    TableId: 2,
    TextLength: null,
    Precision: null,
    Scale: null,
    IsUnique: null,
    IsUnicode: null,
    MinNumber: null,
    MaxNumber: null,
    MinDate: null,
    MaxDate: null,
    RegExValidation: null,
    RegExValidationMessaje: null,
    DateTimeDefaultValue: null,
    StringDefaultValue: null,
    NumericDefaultValue: null,
    BooleanDefaultValue: null,
    ImageHeight: null,
    ImageWidth: null,
    LookupTableId: null,
    LookupReferencedCollectionName: null,
    Formula: null,
    CustomConfig:
      '{"DisplayNameTranslations":{"es":"Archivos iniciales"},"DescriptionTranslations":{"es":""}, "fileSettings": {"isMultiple":false, "allowedExtensions":["img"], "minFileSize": 10000, "maxFileSize": 1500000, "minFilesCount": 1, "maxFilesCount": 3},"relatedTable":{"tableName":"Departments2__Files","relatedColumnName":"ParentEntity","isWeakRelationship":true}}',
    DatabaseConfig: null,
    AvailableOnInsert: null,
    AvailableOnUpdate: null,
    MajorVersion: null,
    MinorVersion: null,
    ReleasedVersionHId: null,
    RowVersion: null,
    CreatedDate: "2023-08-16T12:39:37.047Z",
    CreatedUserId: 1,
    ModifiedDate: "2023-08-16T12:39:37.047Z",
    ModifiedUserId: 1,
    DeletedDate: null,
    DeletedUserId: null,
  },
];

export { TableSettingsDialog };
